from pyspark.sql.types import DateType, StringType, StructField, StructType, TimestampType

ORDER_ITEM_SCHEMA = StructType([
    StructField("order_item_id", StringType()),
    StructField("order_id", StringType()),
    StructField("variant_id", StringType()),
    StructField("vendor_id", StringType()),
    StructField("product_name_snapshot", StringType()),
    StructField("sku_snapshot", StringType()),
    StructField("quantity_ordered", StringType()),
    StructField("quantity_cancelled", StringType()),
    StructField("quantity_fulfilled", StringType()),
    StructField("quantity_returned", StringType()),
    StructField("unit_price", StringType()),
    StructField("line_discount_amount", StringType()),
    StructField("line_tax_amount", StringType()),
    StructField("line_shipping_amount", StringType()),
    StructField("line_total_amount", StringType()),
    StructField("currency_code", StringType()),
    StructField("item_status", StringType()),
    StructField("created_at", StringType()),
    StructField("updated_at", StringType()),
])

ORDER_ITEM_BRONZE_SCHEMA = StructType([
    StructField("order_item_id", StringType()),
    StructField("order_id", StringType()),
    StructField("variant_id", StringType()),
    StructField("vendor_id", StringType()),
    StructField("product_name_snapshot", StringType()),
    StructField("sku_snapshot", StringType()),
    StructField("quantity_ordered", StringType()),
    StructField("quantity_cancelled", StringType()),
    StructField("quantity_fulfilled", StringType()),
    StructField("quantity_returned", StringType()),
    StructField("unit_price", StringType()),
    StructField("line_discount_amount", StringType()),
    StructField("line_tax_amount", StringType()),
    StructField("line_shipping_amount", StringType()),
    StructField("line_total_amount", StringType()),
    StructField("currency_code", StringType()),
    StructField("item_status", StringType()),
    StructField("created_at", StringType()),
    StructField("updated_at", StringType()),
    StructField("kafka_key", StringType()),
    StructField("kafka_topic", StringType()),
    StructField("kafka_partition", StringType()),
    StructField("kafka_offset", StringType()),
    StructField("ingestion_timestamp", TimestampType()),
    StructField("ingestion_date", DateType()),
])
