from pyspark.sql.types import DateType, StringType, StructField, StructType, TimestampType

ORDER_SCHEMA = StructType([
    StructField("order_id", StringType()),
    StructField("customer_id", StringType()),
    StructField("sales_channel_id", StringType()),
    StructField("order_number", StringType()),
    StructField("order_status", StringType()),
    StructField("fulfillment_status", StringType()),
    StructField("payment_status", StringType()),
    StructField("order_timestamp", StringType()),
    StructField("currency_code", StringType()),
    StructField("subtotal_amount", StringType()),
    StructField("discount_amount", StringType()),
    StructField("tax_amount", StringType()),
    StructField("shipping_amount", StringType()),
    StructField("total_amount", StringType()),
    StructField("created_at", StringType()),
    StructField("updated_at", StringType()),
    StructField("is_deleted", StringType()),
])

ORDER_BRONZE_SCHEMA = StructType([
    StructField("order_id", StringType()),
    StructField("customer_id", StringType()),
    StructField("sales_channel_id", StringType()),
    StructField("order_number", StringType()),
    StructField("order_status", StringType()),
    StructField("fulfillment_status", StringType()),
    StructField("payment_status", StringType()),
    StructField("order_timestamp", StringType()),
    StructField("currency_code", StringType()),
    StructField("subtotal_amount", StringType()),
    StructField("discount_amount", StringType()),
    StructField("tax_amount", StringType()),
    StructField("shipping_amount", StringType()),
    StructField("total_amount", StringType()),
    StructField("created_at", StringType()),
    StructField("updated_at", StringType()),
    StructField("is_deleted", StringType()),
    StructField("kafka_key", StringType()),
    StructField("kafka_topic", StringType()),
    StructField("kafka_partition", StringType()),
    StructField("kafka_offset", StringType()),
    StructField("ingestion_timestamp", TimestampType()),
    StructField("ingestion_date", DateType()),
])
