from pyspark.sql.types import DateType, StringType, StructField, StructType, TimestampType

PROMOTION_SCHEMA = StructType([
    StructField("promotion_id", StringType()),
    StructField("promotion_name", StringType()),
    StructField("promotion_code", StringType()),
    StructField("promotion_type", StringType()),
    StructField("discount_percentage", StringType()),
    StructField("discount_amount", StringType()),
    StructField("minimum_purchase_amount", StringType()),
    StructField("maximum_discount_cap", StringType()),
    StructField("applicable_to", StringType()),
    StructField("applicable_entity_id", StringType()),
    StructField("usage_limit", StringType()),
    StructField("usage_count_per_customer", StringType()),
    StructField("valid_from", StringType()),
    StructField("valid_until", StringType()),
    StructField("is_active", StringType()),
    StructField("created_at", StringType()),
    StructField("updated_at", StringType()),
    StructField("is_deleted", StringType()),
])

PROMOTION_BRONZE_SCHEMA = StructType([
    StructField("promotion_id", StringType()),
    StructField("promotion_name", StringType()),
    StructField("promotion_code", StringType()),
    StructField("promotion_type", StringType()),
    StructField("discount_percentage", StringType()),
    StructField("discount_amount", StringType()),
    StructField("minimum_purchase_amount", StringType()),
    StructField("maximum_discount_cap", StringType()),
    StructField("applicable_to", StringType()),
    StructField("applicable_entity_id", StringType()),
    StructField("usage_limit", StringType()),
    StructField("usage_count_per_customer", StringType()),
    StructField("valid_from", StringType()),
    StructField("valid_until", StringType()),
    StructField("is_active", StringType()),
    StructField("created_at", StringType()),
    StructField("updated_at", StringType()),
    StructField("is_deleted", StringType()),
    StructField("kafka_key", StringType()),
    StructField("kafka_topic", StringType()),
    StructField("kafka_partition", StringType()),
    StructField("kafka_offset", StringType()),
    StructField("ingestion_timestamp", TimestampType()),
    StructField("ingestion_date", DateType()),
])
