name: 'dbt_retail'
version: '1.0.0'
config-version: 2

profile: 'dbt_retail' # This MUST match the name in your profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_retail:
    # This automatically structures your target schemas in Snowflake
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table